# write mysql service

version: '3.7'
services: 
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-root}"
      MYSQL_DATABASE: "${DB_NAME:-test}"
    ports:
      - 3306:3306
